### ISSUE TITLE
Помогите, пожалуйста.

### ISSUE THREAD

**Issue by erxson** [EasyDonate/EasyDonate4J#2]
Здравствуйте! Помогите мне, пожалуйста, с EasyDonate4J. Я читал документацию на вики гитхаба, но че-то не осилил всё чикипукнуть. По задумке должен получиться майнкрафт плагин для отправки информации о новых донатах на дискорд вебхук. Вот получившийся код без лишних методов.
https://pastes.dev/6yHjp67yK8
Я вам еще на почту писал, там сообщение поподробнее есть. Сюда я пишу уже спустя пару дней.

**Comment by SoKnight** [comment]
Здравствуйте.
Я не понимаю, что конкретно Вы хотите от нас :/
Я посмотрел Ваш код, состоящий в основном из всего, что есть в документации о Callback API.
Сама реализация Callback API в EasyDonate4J должна быть рабочей, т.к. тестировалась перед релизом.
Мы не будем писать плагин вместо Вас, вместо этого мы итак Вам предоставляем готовую библиотеку.
Работайте над решением своих ошибок самостоятельно, используйте доступные инструменты отладки, чтобы найти причину. Если ошибка окажется на нашей стороне, и Вы точно будете в этом уверены, создайте, пожалуйста, новый Issue.

**Comment by erxson** [comment]
Понял, спасибо. Я еще до этого обращался в поддержку с этим, но мне сказали, что не знают как помочь и направили сюда. Извиняюсь.

**Comment by SoKnight** [comment]
Всё нормально.
Просто здесь, в Issues, я ожидаю увидеть скорее содержательные сообщения о том, что что-то неправильно работает в коде библиотеки, а не просьбы о своего рода сопровождении разработки какого-то другого решения на базе неё.
Я поработал над документацией в wiki, ожидая, что она будет достаточно содержательной и полезной, чтобы не было подобных Issue, но они всё равно есть :D
